keyboard: nanosic_driver: Fix missing identifier for xiaomi_keyboard_init()
This fixes following error:
In file included from ../drivers/input/keyboard/nanosic_driver/nano_chardev.c:33:
../drivers/input/keyboard/nanosic_driver/nano_macro.h:285:32: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  285 | __attribute__((unused)) static xiaomi_keyboard_init(struct nano_i2c_client* i2c_client);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      | int
1 error generated.

Change-Id: I1f171ae3f05fe898b6362ed49d8fbd10d7e06a0c
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>