touchscreen: goodix_9916: Fix false positive unused function error
Fixes:
../drivers/input/touchscreen/goodix_9916/goodix_brl_spi.c:41:19: error: unused function 'setup_get_display_cmdline' [-Werror,-Wunused-function]
   41 | static int __init setup_get_display_cmdline(char *str)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: Id377200e1d155311a8ca6e2db31550d3fdafcb00
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>