touchscreen: fts_{521,spi}: Fix potential buffer overflow in fts_driver_test_write
Fixes following errors:
../drivers/input/touchscreen/fts_spi/fts_proc.c:483:24: error: 'sscanf' may overflow; destination buffer in argument 3 has size 100, but the corresponding specifier may require size 101 [-Werror,-Wfortify-source]
  483 |                                 sscanf(p, "%100s", path);
      |                                                    ^

../drivers/input/touchscreen/fts_521/fts_proc.c:483:24: error: 'sscanf' may overflow; destination buffer in argument 3 has size 100, but the corresponding specifier may require size 101 [-Werror,-Wfortify-source]
  483 |                                 sscanf(p, "%100s", path);
      |                                                    ^

The above errors indicates that the `sscanf` function might overflow the
destination buffer `path` because the format specifier `%100s` could potentially
write a string of 100 characters plus a null terminator, exceeding the buffer
size of 100 characters.

So, to fix that simply increase the buffer size for path to 101 to accommodate
the null terminator.

Change-Id: Icc977a4531af2f3e5200f41bb180d73fc1d91fcf
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>